todo/src/todo/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog

urlpatterns =  [
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('admin/', admin.site.urls),
    path('',include('tudu.urls'))
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/src/tudu/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'tudu'

urlpatterns = [

    path("", HomeView.as_view(), name="index"),
    path("sorry-not-allowed/", NoPermissionView.as_view(), name="no_permission"),
    path("search/", SearchView.as_view(), name="search"),
    path('sort/', SortByOrder.as_view(), name='sort'),

    path('add-project/', ProjectCreateView.as_view(), name='project'),
    path('project-detail/<slug:slug>/', ProjectDetailView.as_view(), name='project_detail'),
    path('update-project/<slug:slug>', ProjectUpdateView.as_view(), name='project_update'),
    path('delete-project/<slug:slug>', ProjectDeleteView.as_view(), name='project_delete'),

    path("issue/", IssueListView.as_view(), name="issue_list"),
    path('project/<slug:slug>', IssueCreateView.as_view(), name='issue'),
    path('project/update-issue/<slug:slug>', IssueUpdateView.as_view(), name='issue_update'),
    path('project/delete-issue/<slug:slug>', IssueDeleteView.as_view(), name='issue_delete'),
    path('project/<slug:slug>/<int:pk>', IssueDetailView.as_view(), name='issue_detail'),

    path('users/', UserListView.as_view(), name='users'),
    path('update-users/<int:pk>', UserUpdateView.as_view(), name='user_update'),
    path('delete-users/<int:pk>', UserDeleteView.as_view(), name='user_delete'),
    path('user/<int:pk>', UserDetailView.as_view(), name='user_detail'),

    path('registration/', AdminRegistrationView.as_view(), name='registration'),
    path('login/', LoginView.as_view(template_name='adminportal/login.html'), name='login'),
    path('logged-out/', LogoutView.as_view(template_name='adminportal/login.html'), name='logout'),

    path('over-estimated-tasks/', views.over_estimated_tasks, name='over_estimated_tasks'),
    path('under-estimated-tasks/', views.under_estimated_tasks, name='under_estimated_tasks'),
    path('delayed-tasks/', views.delayed_tasks, name='delayed_tasks'),
    
]

todo/src/templates/adminportal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin </title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'adminportal/vendors/feather/feather.css' %}">
    <link rel="stylesheet" href="{% static 'adminportal/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminportal/vendors/ti-icons/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'adminportal/vendors/typicons/typicons.css' %}">
    <link rel="stylesheet" href="{% static 'adminportal/vendors/simple-line-icons/css/simple-line-icons.css' %}">
    <link rel="stylesheet" href="{% static 'adminportal/vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- <link rel="stylesheet" href="{% static 'adminportal/vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}"> -->
    <link rel="stylesheet" href="{% static 'adminportal/js/select.dataTables.min.css' %}">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'adminportal/css/vertical-layout-light/style.css' %}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{% static 'adminportal/images/favicon.png' %}" />

    <!-- HTMX TAGS -->
    <!-- jsDelivr :: Sortable :: Latest (https://www.jsdelivr.com/package/npm/sortablejs) -->
    <script src="https://unpkg.com/htmx.org@1.6.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script> {% block head %} {% endblock %}
</head>

<body>

    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
                <div class="me-3">
                    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-bs-toggle="minimize">
                        <span class="icon-menu"></span>
                    </button>
                </div>
                <div>
                    <a class="navbar-brand brand-logo" href="{% url 'tudu:index' %}">
                        <img src="{% static 'adminportal/images/logo.svg' %}" alt="logo" />
                    </a>
                    <a class="navbar-brand brand-logo-mini" href="index.html">
                        <img src="{% static 'adminportal/images/logo-mini.svg' %}" alt="logo" />
                    </a>
                </div>
            </div>

            <div class="navbar-menu-wrapper d-flex align-items-top">
                {% block nav_head %}

                <ul class="navbar-nav">
                    <li class="nav-item font-weight-semibold d-none d-lg-block ms-0">
                        <h1 class="welcome-text">Hey There, <span class="text-black fw-bold">{{ user.username }} </span>
                        </h1>
                        <h3 class="welcome-sub-text">We are happy to have you here. </h3>
                    </li>
                </ul>
                {% endblock %}

                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <h3 class="welcome-sub-text">Designation: {{ user.designation }} </h3>
                    </li>

                    <li class="nav-item">
                        <form class="search-form" action="{% url 'tudu:search' %}">
                            <i class="icon-search"></i>
                            <input type="text" name="issues" class="form-control" placeholder="Search Issue" title="Search here">
                            <button type="submit" class="btn"></button>

                        </form>
                    </li>
                    <li class="nav-item dropdown d-none d-lg-block user-dropdown">
                        <a class="nav-link" id="UserDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                            <img class="img-xs rounded-circle" src="{{ user.profile_pic.url }}" alt="Profile image">
                        </a>
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
                            <div class="dropdown-header text-center">
                                {% comment %} <img class="img-sm rounded-circle" src="{{ Admin.profile_pic.url }}" alt="Admin.profile_pic.url"> <br>
                                <img class="img-sm rounded-circle" src="{{ admin.profile_pic.url }}" alt="admin.profile_pic.url"> <br>
                                <img class="img-sm rounded-circle" src="{{ user.profile_pic.url }}" alt="user.profile_pic.url"><br>
                                <img class="img-sm rounded-circle" src="{{ user.profile_pic }}" alt="user.profile_pic"><br>
                                <img class="img-sm rounded-circle" src="{{ user.imageURL }}" alt="user.imageURL"><br>
                                <img class="img-sm rounded-circle" src="{{ request.user.imageURL }}" alt="request.user.imageURL"><br> {% endcomment %}

                                <p class="mb-1 mt-3 font-weight-semibold"> {{ user.username }} </p>
                                <p class="fw-light text-muted mb-0"> {{ user.email }}</p>
                            </div>
                            <a class="dropdown-item"><i
                                    class="dropdown-item-icon mdi mdi-account-outline text-primary me-2"></i> My Profile
                                <span class="badge badge-pill badge-danger">1</span></a>
                            <!-- <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-message-text-outline text-primary me-2"></i> Messages</a>
                            <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-calendar-check-outline text-primary me-2"></i> Activity</a>
                            <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-help-circle-outline text-primary me-2"></i> FAQ</a> -->
                            <a class="dropdown-item" href="{% url 'tudu:logout' %}"><i class="dropdown-item-icon mdi mdi-power text-primary me-2"></i>Sign Out</a>
                        </div>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-bs-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav" style="position: fixed;">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tudu:index' %}">
                            <i class="mdi mdi-grid-large menu-icon"></i>
                            <span class="menu-title">Home</span>
                        </a>
                    </li>
                    <li class="nav-item nav-category">User Data</li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tudu:users' %}" aria-expanded="false" aria-controls="ui-basic">
                            <i class="menu-icon mdi mdi-account menu-icon"></i>
                            <span class="menu-title">User</span>
                            <i class="menu-arrow"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tudu:registration' %}" aria-expanded="false" aria-controls="ui-basic">
                            <i class="menu-icon mdi  mdi-account-plus"></i>
                            <span class="menu-title">Register</span>
                            <i class="menu-arrow"></i>
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tudu:logout' %}" aria-expanded="false" aria-controls="ui-basic">
                            <i class="menu-icon mdi mdi-logout menu-icon"></i>
                            <span class="menu-title">Log-Out</span>
                            <i class="menu-arrow"></i>
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tudu:login' %}" aria-expanded="false" aria-controls="ui-basic">
                            <i class="menu-icon mdi mdi-login menu-icon"></i>
                            <span class="menu-title">Log-In</span>
                            <i class="menu-arrow"></i>
                        </a>
                    </li>
                    {% endif %}

                    <li class="nav-item nav-category">Projects & Issues</li>
                    {% if not user.designation == "Developer" %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tudu:index' %}" aria-expanded="false" aria-controls="form-elements">
                            <i class="menu-icon mdi mdi-folder-plus "></i>
                            <span class="menu-title">Projects</span>
                            <i class="menu-arrow"></i>
                        </a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tudu:issue_list' %}" aria-expanded="false" aria-controls="form-elements">
                            <i class="menu-icon mdi mdi-filter "></i>
                            <span class="menu-title">Issues</span>
                            <i class="menu-arrow"></i>
                        </a>
                    </li>

                    <li class="nav-item nav-category">Reports</li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="collapse" href="#ui-report" aria-expanded="false" aria-controls="form-elements">
                            <i class="menu-icon mdi mdi-file-document "></i>
                            <span class="menu-title">Reports</span>
                            <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse" id="ui-report">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'tudu:over_estimated_tasks' %}" target="_blank">
                                        Over-Estimated-Issues
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'tudu:under_estimated_tasks' %}" target="_blank">
                                        Under-Estimated-Issues
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'tudu:delayed_tasks' %}" target="_blank">
                                        Delayed-Issues
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>

                </ul>
            </nav>
            {% block body_block %}{% endblock %}

        </div>
        <!-- partial:partials/_sidebar.html -->
    </div>




    <!-- plugins:js -->

    <script src="{% static 'adminportal/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="{% static 'adminportal/vendors/chart.js/Chart.min.js' %}"></script>
    <!-- <script src="{% static 'adminportal/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script> -->
    <script src="{% static 'adminportal/vendors/progressbar.js/progressbar.min.js' %}"></script>

    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'adminportal/js/off-canvas.js' %}"></script>
    <script src="{% static 'adminportal/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'adminportal/js/template.js' %}"></script>
    <script src="{% static 'adminportal/js/settings.js' %}"></script>
    <script src="{% static 'adminportal/js/todolist.js' %}"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="{% static 'adminportal/js/jquery.cookie.js' %}" type="text/javascript"></script>
    <script src="{% static 'adminportal/js/dashboard.js' %}"></script>
    <script src="{% static 'adminportal/js/Chart.roundedBarCharts.js' %}"></script>
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })

        htmx.onLoad(function(content) {
            var sortables = content.querySelectorAll(".sortable ");
            for (var i = 0; i < sortables.length; i++) {
                var sortable = sortables[i];
                new Sortable(sortable, {
                    animation: 150,
                    ghostClass: 'blue-background-class'
                });
            }
        })
    </script>

    {% block scripts %} {% endblock %}
    <!-- End custom js for this page-->
</body>

</html>

todo/src/templates/adminportal/index.html
{% extends 'adminportal/base.html' %} {% load static %} {% block head %}
<title>Admin</title>
<style>
    table {
        table-layout: fixed;
    }
</style>
{% endblock %} {% block nav_head %}
<nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
        <div class="me-3">
            <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-bs-toggle="minimize">
                        <span class="icon-menu"></span>
                    </button>
        </div>
        <div>
            <a class="navbar-brand brand-logo" href="{% url 'tudu:index' %}">
                <img src="{% static 'adminportal/images/logo.svg' %}" alt="logo" />
            </a>
            <a class="navbar-brand brand-logo-mini" href="index.html">
                <img src="{% static 'adminportal/images/logo-mini.svg' %}" alt="logo" />
            </a>
        </div>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-top">
        <ul class="navbar-nav">
            <li class="nav-item font-weight-semibold d-none d-lg-block ms-0">
                <h1 class="welcome-text">Hey There, <span class="text-black fw-bold">{{ user.username }}</span>
                </h1>
                <h3 class="welcome-sub-text"> We are happy to have you here. </h3>
            </li>
        </ul>
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <h3 class="welcome-sub-text">Designation: {{ user.designation }} </h3>
            </li>

            <li class="nav-item">
                <form class="search-form" action="{% url 'tudu:search' %}">
                    <i class="icon-search"></i>
                    <input type="text" name="projects" class="form-control" placeholder="Search Project" title="Search here">
                    <button type="submit" class="btn"></button>
                </form>
            </li>
            <li class="nav-item dropdown d-none d-lg-block user-dropdown">
                <a class="nav-link" id="UserDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                    <img class="img-xs rounded-circle" src="{{ request.user.profile_pic.url }}" alt="Profile image">
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
                    <div class="dropdown-header text-center">


                        <p class="mb-1 mt-3 font-weight-semibold"> {{ user.username }} </p>
                        <p class="fw-light text-muted mb-0"> {{ user.email }}</p>
                    </div>
                    <a class="dropdown-item"><i
                                    class="dropdown-item-icon mdi mdi-account-outline text-primary me-2"></i> My Profile
                                <span class="badge badge-pill badge-danger">1</span></a>
                    <!-- <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-message-text-outline text-primary me-2"></i> Messages</a>
                            <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-calendar-check-outline text-primary me-2"></i> Activity</a>
                            <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-help-circle-outline text-primary me-2"></i> FAQ</a> -->
                    <a class="dropdown-item" href="{% url 'tudu:logout' %}"><i class="dropdown-item-icon mdi mdi-power text-primary me-2"></i>Sign Out</a>
                </div>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-bs-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
    </div>
</nav>
{% endblock %} {% block body_block %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">
                            {% if user.designation == "Admin" %}
                            <a href="{% url 'tudu:project' %}" style="margin-left: 85%; " class="btn btn-outline-primary float-left" type="button">
                                Add Project
                            </a> {% endif %} Project Table
                        </h4>
                        <!-- <div class="table-responsive">
                            {% for message in messages %}
                            <div style="color:rgb(1, 9, 119);" class="alert alert-success alert-dismissible" role="alert">
                                {{ message }}
                            </div>
                            {% endfor %}                        </div> -->
                        <div class="row">
                            <table class="table" style="margin-left: 30px;">
                                <thead style="margin-left: 50px;">
                                    <tr>

                                        <th>Name</th>
                                        <th>Assign-To</th>
                                        <th>Status </th>
                                        <th>Discription</th>
                                        {% if not user.designation == "Developer" %}
                                        <th>Edit/Delete </th>
                                        {% endif %}
                                    </tr>
                                </thead>
                            </table>
                        </div>
                        <form class="sortable" hx-post="{% url 'tudu:sort' %}" hx-trigger="end" hx-target="#task-list">
                            {% for prod in items %}
                            <div class="row">
                                <input type='hidden' name='item' value='{{ prod.id }}' />
                                <div>
                                    <!-- <tbody> -->
                                    <table class=" {% if prod.status == 'NotStarted' %} table table-danger {% elif prod.status == 'Pending' %} table table-warning {% elif prod.status == 'Completed' %}table table-success {% endif %}">
                                        <tr>
                                            <td>
                                                <a href="{{ prod.get_absolute_url }}" style="text-decoration: none; color: black;">
                                                    <h6>{{ prod.title|truncatechars:20 }} </h6>
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{% url 'tudu:user_detail' prod.assign_to.id %}" style="text-decoration: none; color: black;">
                                                    <h6>
                                                        {{ prod.assign_to }}
                                                    </h6>
                                                </a>
                                                {{ prod.assign_to.designation }}
                                            </td>
                                            <td>
                                                <!-- <button class="btn btn-primary" ><i class="mdi mdi-hand-pointing-right"></i></button> -->
                                                {% if prod.status == "NotStarted" %} <label class="badge badge-danger">{{prod.status}}</label>
                                                <p>
                                                </p>
                                                <div class="progress">
                                                    <div class="progress-bar" role="progressbar" style="background-color: #0d19fd;"></div>
                                                </div>
                                                {% elif prod.status == "Pending" %} <label class="badge badge-warning">{{prod.status}}</label>
                                                <p>
                                                </p>
                                                <div class="progress">
                                                    <div class="progress-bar" role="progressbar" style="width: 51%; background-color: orange;"></div>
                                                </div>
                                                {% elif prod.status == "Completed" %} <label class="badge badge-success">{{prod.status}}</label>
                                                <p>
                                                </p>
                                                <div class="progress">
                                                    <div class="progress-bar" role="progressbar" style="width: 100%; background-color: #0dfd0d;"></div>
                                                </div>
                                                {% endif %}
                                            </td>
                                            <td>{{prod.discription|title|truncatechars:25}}</td>


                                            {% if not user.designation == "Developer" %}
                                            <td>
                                                {% if prod.assign_to.username == request.user.username or request.user.designation == "Admin" or not prod.status == "Completed" %}

                                                <a href="{% url 'tudu:project_update' prod.slug %}" type="button" class="btn btn-warning" style="padding: 6px;">
                                                    <span class="mdi mdi-grease-pencil"></span>
                                                </a>
                                                <a style="padding: 5px;"> </a>
                                                <a href="{% url 'tudu:project_delete' prod.slug %}" type="button" class="btn btn-danger" style="padding: 6px;">
                                                    <span class="mdi mdi-delete-empty"></span>
                                                </a>
                                                {% endif %}
                                            </td>
                                            {% endif %}
                                        </tr>
                                    </table>
                                    <!-- </tbody> -->
                                </div>
                            </div>
                            {% endfor %}
                        </form>

                        <div style="display: none;" id="task-list">
                        </div>

                    </div>
                    <!-- </table> -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- content-wrapper ends -->

<!-- partial -->
</div>
{% endblock %} {% block scripts %} {% endblock %}

todo/src/templates/adminportal/user_detail.html
{% extends 'adminportal/base.html' %} {% load static %} {% block head %}
<title>Admin</title>



{% endblock %} {% block body_block %}
<!-- Page Content -->



<div class="container ">

    <!-- Portfolio Item Heading -->
    <h3 class="my-4 "> <small>User,  </small> {{ object.username }}
    </h3>

    <!-- Portfolio Item Row -->

    <div class="row ">

        <div class="col-md-5 ">
            <img class="img-fluid " src="{{ object.profile_pic.url }} " alt="attachments here if any..!! " style="height: 100%; ">
        </div>

        <div class="col-md-7 ">
            <!-- <h3 class="my-3 ">User Description</h3>
            <p>
                {{object.discription}}
            </p> -->
            <h3 class="my-3 " style="text-decoration: underline; ">User Details</h3>
            <l>
                <h4>
                    <li>Email: {{object.email}}</li>
                    <li>Designation: {{ object.designation }}</li>
                    <li>Experties: {{object.experties}}</li>
                    <li>Joined Date: {{object.created_at}} </li>
                    {% if user.designation == "Admin " or user.username == object.username %}
                    <li>Edit/Delete:
                        <a href="{% url 'tudu:user_update' object.id %} " type="button " class="btn btn-warning " style="padding: 6px; ">
                            <span class="mdi mdi-grease-pencil "></span>
                        </a>
                        <a href="{% url 'tudu:user_delete' object.id %} " style="padding: 5px; "> </a>
                        <a type="button " class="btn btn-danger " style="padding: 6px; ">
                            <span class="mdi mdi-delete-empty "></span>
                        </a>
                    </li>
                    {% endif %}
                </h4>
                </ul>
        </div>

    </div>

    <!-- Related Projects Row -->

    <div class="row ">
        <div class="col-md-5 ">
            <h3 class="my-4 " style="text-decoration: underline; ">Assigned Projects</h3>
            <ul>
                {% for project in project_user %}
                <h4>
                    <a href="{{project.get_absolute_url}} " style="text-decoration: none; color: black; ">
                        <li>{{ project.title }}</li>
                    </a>
                </h4>
                {% endfor %}

            </ul>
        </div>
        {% if not object.designation == "Developer " %} {% endif %}

        <div class="col-md-5 ">
            <h3 class="my-4 " style="text-decoration: underline; ">Assigned Issues - Project</h3>

            {% for issue in issue_user %}
            <ul>
                <h4>
                    <li>
                        <a href="{{issue.get_absolute_url}} " style="text-decoration: none; color: black; ">
                            {{ issue.title }}
                        </a>:
                        <a href="{% url 'tudu:project_detail' issue.project_name.slug %} " style="text-decoration: none; color: black; ">
                            {{ issue.project_name }}
                        </a>
                    </li>
                </h4>


            </ul>
            {% endfor %}
        </div>

    </div>

</div>

<!-- /.container -->
{% endblock %} {% block scripts %}


<script>
    document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
</script>
{% endblock %}